# do not use Travis python to save some time
language: generic
os: linux
dist: xenial

jobs:
  fast_finish: true
  include:
    - name: conda-deploy

# install miniconda and create environment
before_install:
  - echo "Installing miniconda.";
  - mkdir $HOME/download;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
  - bash $HOME/download/miniconda.sh -b -u -p $HOME/miniconda;
  - echo "creating scpy environment";
  - source "$HOME/miniconda/etc/profile.d/conda.sh";
  - hash -r;
  - conda config --set always_yes yes;
  - conda config -q --set anaconda_upload no
  - conda update -q conda;
  - conda create -n scpy;

# create env and install scpy from sources
install:
  - echo "Activate scpy environnment...";
  - source "$HOME/miniconda/etc/profile.d/conda.sh";
  - conda activate scpy;
  - conda install conda-build anaconda-client conda-verify
  - git fetch --tags;

script:
  - bash ./conda_upload.sh;
